# Основные настройки workflow
name: CI/CD Pipeline for Elastic Beanstalk

# Переменные окружения
env:
  EB_PACKAGE_S3_BUCKET_NAME: "NameOfBucket"    # Имя S3 бакета для артефактов
  EB_APPLICATION_NAME: "MyFlask"               # Название приложения Elastic Beanstalk
  EB_ENVIRONMENT_NAME: "MyFlask-env"           # Название окружения Elastic Beanstalk
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"  # Имя ZIP-архива с хешем коммита
  AWS_REGION_NAME: "us-west-2"                 # Регион AWS

# Триггеры выполнения
on:
  push:
    branches:
      - master  # Запускать только при пуше в ветку master

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest  # Окружение для выполнения

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Git clone Repo
        uses: actions/checkout@v4  # Исправлено: правильное название действия и версия

      # Шаг 2: Создание ZIP-архива
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*  # Исправлен синтаксис

      # Шаг 3: Настройка учетных данных AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      # Шаг 4: Загрузка артефакта в S3
      - name: Upload Package to S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}

      # Шаг 5: Уведомление об окончании CI-стадии
      - name: Print CI Success Message
        run: echo "CI Pipeline part finished successfully!"

      # Шаг 6: Создание нового приложения Elastic Beanstalk
      - name: Create Elastic Beanstalk Application
        run: |
          aws elasticbeanstalk create-application \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
            --version-label "Version-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"

      # Шаг 7: Деплой в окружение Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
            --version-label "Version-${{ github.sha }}"

      # Шаг 8: Уведомление об окончании CD-стадии
      - name: Print CD Success Message
        run: echo "CD Pipeline part finished successfully!"
