name:
  env:
    EB_PACKEGE_S3_BUCKET_NAME   : "NameOfBucket"      
    EB_APPLICTATION_NAME        : "MyFlask"
    EB_ENCIROMENT_NAME          : "MyFlask-env"
    DEPLOY_PACKEGE_NAME         : "flask_app_${{ github.sha }}.zip"
    AWS_REGION_NAME             : "us-west-2"

  on:
    Push:
    branches:
    - master

  jobs:
    my_ci_part:
    runs-on   : ubuntu-latest

    steps:
      - name  : Git clone Repo
        uses  : action/checout@v1

      - name  : Create ZIP deploymaent package
        run   : zip -r {{ env.`DEPLOY_PACKEGE_NAME}} ./ -x *.git*

      - name  : Configure my AWS Credentials
        uses  : aws-actions/configure-aws-credentionals@v1
        with:
        aws-acces-key-id    : ${{ secrets.MY_AWS_ACESS_KEY }}
        aws-secret-acess-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region          : ${{ env.AWS_REGION_NAME }}

      - name  : Deployment Package to S3 Backet
        run   : aws s3 cp ${{ env.DEPLOY_PACKEGE_NAME }} s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}
      - name  : Print Happy Message for CI finish
        run   : echo "CI Pipline part finished succefully!"

      - name  : Create new ElastickBeanstalk Application
        run   : aws elasticbeanstalk create-application --application-name ${{ env.EB_APPLICTATION_NAME }} --source-bundle S3Bucket="${{ env.EB_PACKEGE_S3_BUCKET_NAME }}"",S3Key="${{ env.DEPLOY_PACKEGE_NAME }}" --version-label "Version-${{ github.sha }}" --description "CommitSHA-${{ github.sha }}"

      - name  : Deploy new ElastickBeanstalk Application
        run   : aws elasticbeanstalk update-environment --application-name ${{ env.EB_APPLICTATION_NAME }} --environment-name ${{ env.EB_ENCIROMENT_NAME }} --version-label "Version-${{ github.sha }}"

      - name  : Print Happy Message for CD finish
        run   : echo "CD Pipline part finished succefully!"
